## Steps
- Load the librararies - numpy, sklearn  (Scientific Kit Learning)
- Load the data
- Load the model
- Model fitting (training) ==> output based on the algorithm (line for linear Regression)
- Evaluation Score: RMSE, R2

### Data - Q.1:
- x: 1 2 3 4 5 6 7 8 9 10
- y: 2.8 5.1 7.0 9.2 11.1 12.9 15.2 17.0 18.9 21.1

In [9]:
import numpy as np
import sklearn as sk
from sklearn.linear_model import LinearRegression

The SKLearn Library supports only Arrays for LinearRegression

In [65]:
x = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]]).reshape(10,1)
#print(x)

# Label
y = np.array([2.8, 5.1, 7.0, 9.2, 11.1, 12.9, 15.2, 17.0, 18.9, 21.1])
#print(y)

In [66]:
# Load the LinearRegression model
model = LinearRegression()
model.fit(x,y)

,fit_intercept,True
,copy_X,True
,tol,1e-06
,n_jobs,None
,positive,False


### Regression outputs a Line
- y = mx + C
- slope = m
- y_intercept = C

In [23]:
# Print coefficient:
print("coeff", model.coef_)
print("Y-intercept", model.intercept_)

# Predict for unknown X, x= 20
y_pred = model.predict(np.array([20, 10, 33]).reshape(3,1))
print(y_pred)

coeff [2.00666667]
Y-intercept 0.9933333333333305
[41.12666667 21.06       67.21333333]


### Fianlly, Score
- RMSE,
- $R^2$

In [64]:
# We use the trained model to predict 'y' values based on our 'x' inputs
y_pred = model.predict(x)
#print(x)
print(
   np.array(list(zip(x[:,0], y, y_pred, )))
)

[[ 1.          2.8         3.        ]
 [ 2.          5.1         5.00666667]
 [ 3.          7.          7.01333333]
 [ 4.          9.2         9.02      ]
 [ 5.         11.1        11.02666667]
 [ 6.         12.9        13.03333333]
 [ 7.         15.2        15.04      ]
 [ 8.         17.         17.04666667]
 [ 9.         18.9        19.05333333]
 [10.         21.1        21.06      ]]


In [30]:
print("--- Linear Regression Results ---")
from sklearn.metrics import mean_squared_error
slope = model.coef_[0]
intercept = model.intercept_
r_squared = model.score(x, y)
rmse = np.sqrt(mean_squared_error(y, y_pred))
print(f"Equation: y = {slope:.4f}x + {intercept:.4f}")
print(f"R-squared: {r_squared:.4f}")
print(f"RMSE:      {rmse:.4f}")

--- Linear Regression Results ---
Equation: y = 2.0067x + 0.9933
R-squared: 0.9995
RMSE:      0.1254
